### ISSUE TITLE
when i search chinese i have some  issues

### ISSUE THREAD

**Issue by herculesxin** [ViDA-NYU/ache#72] opened 2017-04-05 01:09 UTC
When we crawl Spain website, data_target will appear, and will not appear garbled. When we crawl the Chinese Web site, without data_target, only data_nagetive, and when the URL is GBK-encoding format, the crawl URL garbled when encoding format is UTF-8, crawl the URL to display normal,how can i solve it ?

**Comment by aecio** [comment] 2017-04-06 18:00
I'm not sure if I got the problem. If all pages are classified as irrelevant, the data_target folder won't have any content. Regarding the GBK-encoding issue, can you give more details of what's happening? Only the URL is garbled or the actual content of the page? Which data format are you using to store the data? Can you share the configs you are using?

**Comment by aecio** [comment] 2017-07-03 18:10
Closing due to lack of details to reproduce. Please reopen if you have more details.

**Closed by aecio** 2017-07-03 18:10 UTC
Labels: bug
